on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: |
          npm ci
          npm run build
          touch out/.nojekyll
          sed -i 's/\/\/ //g' next.config.js
          sed -i 's/\/out\///g' .gitignore
          git add out/
          git commit -m 'Deploy'
          git subtree push --prefix out origin gh-pages
